import 'bottomsheet.dart';
class kings{
 final String? name;
 final String? image;
 bottomsheet b1;

  kings({this.name,this.image, required this.b1});
}
List<kings>demokings=[
  kings(name: "Abu Simbel",image:"assets/abu simble.jpg",b1:bottomsheet(name: "Abu Simbel",image: "assets/abu simble.jpg",description:"Abu Simbel is two massive rock-cut temples in the village of Abu Simbel (Arabic: أبو سمبل‎), Aswan Governorate, Upper Egypt, near the border with Sudan.\nThey are situated on the western bank of Lake Nasser, about 230 km (140 mi) southwest of Aswan (about 300 km (190 mi) by road). The complex is part of the UNESCO World Heritage Site known as the NubianMonuments,[1] which run from Abu Simbel downriver to Philae (near Aswan), and include Amada, Wadi es-Sebua, and other Nubian sites. \nThe twin temples were originally carved out of the mountainside in the 13th century BC, during the 19th Dynasty reign of the Pharaoh Ramesses II.")),
  kings(name: "Temple of Deir al-Bahri ",image: "assets/der.jpg",b1:bottomsheet(name: "Temple of Deir al-Bahri ",image: "assets/der.jpg",description:"Deir el-Bahari or Dayr al-Bahri is a complex of mortuary temples and tombs located on the west bank of the Nile, opposite the city of Luxor, Egypt.\n This is a part of the Theban Necropolis. The first monument built at the site was the mortuary temple of Mentuhotep II of the Eleventh Dynasty.\nThe celebrated temple of Hatshepsut (c.1473–1458 BC), the queen who became Pharaoh, is located here, in Deir al-Bahari, on the west bank of Luxor. Made up of three man-made terraces that gradually rise up toward the sheer cliff face, this structure is truly a sight to behold."),),
  kings(name: "Temple of Edfu",image: "assets/habu.jpg",b1:bottomsheet(name: "Temple of Edfu",image: "assets/habu.jpg",description:"Edfu was one of several temples built during the Ptolemaic Kingdom, including the Dendera Temple complex, Esna, the Temple of Kom Ombo, and Philae. Its size reflects the relative prosperity of the time.[4] The present temple, which was begun on 23 August 237 BC, initially consisted of a pillared hall, two transverse halls, and a barque sanctuary surrounded by chapels.\n[5] The building was started during the reign of Ptolemy III Euergetes and completed in 57 BC under Ptolemy XII Auletes.\nIt was built on the site of an earlier, smaller temple also dedicated to Horus, although the previous structure was oriented east-west rather than north-south as in the present site.\nA ruined pylon lies just to the east of the current temple; inscriptional evidence has been found indicating a building program under the New Kingdom rulers Ramesses I, Seti I and Ramesses II."),),
  kings(name: "Medinet Habu",image: "assets/habu.jpg",b1:bottomsheet(name: " Medinet Habu",image: "assets/habu.jpg",description:"Medinet Habu Temple is one of the ancient Egyptian temples in Luxor that was built by pharaoh Ramses III and dedicated to the god Amon. In my opinion, Madinat Habu is one of the best temples on the West Bank, and it's easy to combine with other nearby sites in Egypt like Valley of the Queens or Hatshepsut Temple.\nAside from its size and architectural and artistic importance, the mortuary temple is probably best known as the source of inscribed reliefs depicting the advent and defeat of the Sea Peoples during the reign of Ramesses III.\nThe Temple of Ramesses III at Medinet Habu was an important New Kingdom period temple structure in the West Bank of Luxor in Egypt. Aside from its size and architectural and artistic importance, the mortuary temple is probably best known as the source of inscribed reliefs depicting the advent and defeat of the Sea Peoples during the reign of Ramesses III."),),
  kings(name: "Hathor Temple",image: "assets/hathur.jpg",b1:bottomsheet(name: "Hathor Temple",image: "assets/hathur.jpg",description:"The Temple of Hathor is one of the most well-preserved temples in all of Egypt. There are three temples to view in the complex: the birthing temple at the front, the temple of Isis behind the main temple, and the main temple dedicated to Hathor. There is also a sacred pool that you can still explore.\nThe Temple of Hathor is one of the most well-preserved temples in all of Egypt. There are three temples to view in the complex: the birthing temple at the front, the temple of Isis behind the main temple, and the main temple dedicated to Hathor."),),
  kings(name: "Temple of Karnak",image: "assets/karnakk.jpg",b1:bottomsheet(name: "Temple of Karnak",image: "assets/karnakk.jpg",description:"The complex is a vast open site and includes the Karnak Open Air Museum.\nIt is believed to be the second[citation needed] most visited historical site in Egypt; only the Giza pyramid complex near Cairo receives more visits.\nIt consists of four main parts, of which only the largest is currently open to the general public. The term Karnak often is understood as being the Precinct of Amun-Re only, because this is the only part most visitors see.\nThe three other parts, the Precinct of Mut, the Precinct of Montu, and the dismantled Temple of Amenhotep IV, are closed to the public.\nThere also are a few smaller temples and sanctuaries connecting the Precinct of Mut, the Precinct of Amun-Re, and the Luxor Temple."),),
  kings(name: "kom ombo temple",image: "assets/kom.jpg",b1:bottomsheet(name: "kom ombo temple",image: "assets/kom.jpg",description:"Back in time, the temple took place between the Nubian trade routes and the gold mines in the eastern desert,\nlater, it became a training depot for the wild animals used in the war during the role of Ptolemy VII to fight the Seleucid empire,\nit was built during his reign as well .the area that the temple was constructed on used to be a favorite spot to the crocodiles to lay under the sun on the Nile shore, so it's make sense now to be dedicated to the crocodile god .some renovations were made later, such as the hypostyle hall which was added by Ptolemy the seventh 51-47B.C,Moreover , under the role of emperor Trajan 53-117AD ,the forecourt and outer walls were added"),),
];